name: Build and Archive WPF Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Framework
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8.x'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build the application
        run: msbuild /p:Configuration=Release
